"""empty message

Revision ID: ec9e2f60fbc6
Revises: eaeaad495ec7
Create Date: 2023-07-15 21:18:25.424892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9e2f60fbc6'
down_revision = 'eaeaad495ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_ships')
    op.drop_table('favorites_planets')
    op.drop_table('favorites_char')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_char',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('char_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], name='favorites_char_char_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='favorites_char_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_char_pkey')
    )
    op.create_table('favorites_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='favorites_planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='favorites_planets_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_planets_pkey')
    )
    op.create_table('favorites_ships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], name='favorites_ships_ship_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='favorites_ships_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_ships_pkey')
    )
    op.drop_table('ships_favorites')
    op.drop_table('planets_favorites')
    op.drop_table('character_favorites')
    # ### end Alembic commands ###
