"""empty message

Revision ID: eef2b291534c
Revises: ec9e2f60fbc6
Create Date: 2023-07-18 20:13:48.769414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef2b291534c'
down_revision = 'ec9e2f60fbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=25), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.Column('manufacturer', sa.String(length=250), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=250), nullable=True),
    sa.Column('street_number', sa.String(length=250), nullable=True),
    sa.Column('postal_code', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character__favorite__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet__favorite__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle__favorite__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('characters')
    op.drop_table('planets')
    op.drop_table('character_favorites')
    op.drop_table('planets_favorites')
    op.drop_table('ships_favorites')
    op.drop_table('ships')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    op.create_table('ships',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ships_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('max_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starship_class', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ships_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ships_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], name='ships_favorites_ship_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='ships_favorites_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='ships_favorites_pkey')
    )
    op.create_table('planets_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='planets_favorites_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='planets_favorites_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='planets_favorites_pkey')
    )
    op.create_table('character_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('char_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], name='character_favorites_char_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='character_favorites_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_favorites_pkey')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('climate', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gravity', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='characters_pkey')
    )
    op.drop_table('vehicle__favorite__list')
    op.drop_table('planet__favorite__list')
    op.drop_table('character__favorite__list')
    op.drop_table('address')
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
